#! /bin/sh
# Initial loads upon starting an X server
sxhkd &
compton &
dunst &
mpd &
mpd-notification &
spotify-listener &
/usr/bin/emacs --daemon &
nitrogen --restore &
xrandr --output DP-0 --primary --mode 3840x2160 --pos 0x0 --rotate left --output DP-1 --off --output HDMI-0 --off --output DP-2 --off --output DP-3 --off --output HDMI-1 --off --output DP-4 --mode 3840x2160 --pos 2160x840 --rotate normal --output DP-5 --off
xsetroot -cursor_name left_ptr
~/.config/polybar/launch.sh
# ntfd &
# picom --experimental-backend &

# Dictates which monitor will be the focus, as well as dictates where the bspwm module will be placed in polybar
bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9

# Basic appearance settings
bspc config border_width        3 
bspc config window_gap          6 
bspc config border_radius       2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side 
bspc config pointer_follows_monitor true

# Dicates where applications will open, on which workspace and if intially floated, tiled, etc.
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Gimp-2.10 desktop='^7' state=floating follow=on
bspc rule -a firefoxdeveloperedition desktop='^2' follow=on
bspc rule -a Thunderbird desktop='^4' state=floating follow=on
bspc rule -a Signal desktop='^7' state=tiled follow=on
bspc rule -a spotify desktop='^4' state=floating follow=on
bspc rule -a obs desktop='^8' state=floating follow=on
bspc rule -a Audacity desktop='^8' state=tiled follow=on
bspc rule -a Screenkey manage=off
bspc rule -a KeePassXC state=floating 
bspc rule -a Thunar state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Alacritty state=floating rectangle=1000x700+575+1400

bspc config focused_border_color "#ffffff"

bspc rule -a Alacritty:scratchy sticky=on state=floating rectangle=900x600+600+350
# termite -c scratchterm &
# bspc rule -a scratchterm sticky=on state=floating hidden=on rectangle=900x600+800+450
