#!/bin/sh

spotdl https://open.spotify.com/track/5N20hP6UFF9PzKIaqIjSnw?si=d1f1556e97854389
spotdl https://open.spotify.com/track/7qaa5q7z53J2au70zl84fn?si=feb428ea241a4fa9
spotdl https://open.spotify.com/track/03EsYwfN3RbDhU1kVrfffA?si=1bc5de8120384789
spotdl https://open.spotify.com/track/0vCb70pUXtbCeNIqmEzJyz?si=84b300d73996407e
spotdl https://open.spotify.com/track/5Os2lSlPvvc40Wmun45Tz8?si=0f1806ddd08b4c54
spotdl https://open.spotify.com/track/5QYKmxfPsl69GgeZKDAVSx?si=ae1c99e56d254e65
spotdl https://open.spotify.com/track/3qOkkP9JLltoUvaLjEXTmW?si=8fd6464c3750429a
spotdl https://open.spotify.com/track/5Q5TNh4wr6CPoXKrI2H6gx?si=a21d7f02dcc44427
spotdl https://open.spotify.com/track/2id8E4WvczfKHB4LHI7Np3?si=42e6ab176ca64ee5
